// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jytncxnylnkpdvwquxzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5dG5jeG55bG5rcGR2d3F1eHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjAyNzUsImV4cCI6MjA2NTI5NjI3NX0._FoanSkvE9STrC5_adtVVZIstE2gaQjkLn81jfzGMvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);